name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: your_docker_hub_username
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_USERNAME/my-python-app .
          docker tag $DOCKER_USERNAME/my-python-app $DOCKER_USERNAME/my-python-app:latest
          docker push $DOCKER_USERNAME/my-python-app:latest
